# Generated by Django 4.2.1 on 2023-06-20 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.PositiveIntegerField()),
                ('salary', models.IntegerField()),
                ('experience', models.BooleanField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
